import influxdb_client as client
import oracledb as odb
import configparser
from time import sleep
from record import Record
import json
from  datetime import datetime



config = configparser.ConfigParser()
config.read('src\connect\config.ini')
  
client_influx = client.InfluxDBClient(
            url=config['influx']['url'],
            token= config['influx']['token'],
            org=config['influx']['org'])

dsn = odb.makedsn(config["oracle"]["url"],config["oracle"]["port"],service_name=config["oracle"]["service"])

connect = odb.connect(user=config["oracle"]["user"],password=config["oracle"]["password"],dsn=dsn)

init = True 

def  read_all_temperature(times:str):
    query = f'''
        import "date"
        from(bucket: "cpu_temperature")
        |> range(start:{times})''' + '''
        |> map(fn: (r) => ({
            r with
            captured_time: 
            string(v: date.year(t: r._time))  + "-" +
            (if date.month(t: r._time) < 10 then "0" + string(v: date.month(t: r._time)) else string(v: date.month(t: r._time))) + "-" +
            (if date.monthDay(t: r._time) < 10 then "0" + string(v: date.monthDay(t: r._time)) else string(v: date.monthDay(t: r._time)))
            + " " +
            (if date.hour(t: r._time) < 10 then "0" + string(v: date.hour(t: r._time)) else string(v: date.hour(t: r._time))) + ":" +
            (if date.minute(t: r._time) < 10 then "0" + string(v: date.minute(t: r._time)) else string(v: date.minute(t: r._time))) + ":" +
            (if date.second(t: r._time) < 10 then "0" + string(v: date.second(t: r._time)) else string(v: date.second(t: r._time)))
        }))
        |> drop(columns: ["_measurement","_field"])
        
    '''
    tables = client_influx.query_api().query(query, org=config['influx']['org'])
    result = []
    
    for table in tables:
        for record in table.records:
            result.append({
                "host":record.values.get("host"),
                "sensor_name": record.values.get("sensor"),
                "temperature": record.get_value(),
                "time": datetime.fromisoformat(record.values.get("captured_time"))
            })
    return result

def add_record_oracle(records:Record):
    query = f"insert into cpu_temperature(captured_time, temperature, host_name, sensor_name) values(:time,:temperature,:host,:sensor_name)"
    with connect.cursor() as cursor:
        for record in records:
            print(record)
            cursor.execute(query,record)
    sleep(30)
def creation_of_database():
    query = """
        drop table if  EXISTS CPU_TEMPERATURE;

        CREATE table CPU_TEMPERATURE(
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            captured_time TIMESTAMP(6),
            TEMPERATURE BINARY_DOUBLE,
            HOST_NAME VARCHAR2(100),
            SENSOR_NAME  VARCHAR2(100)
        );

    """
    with connect.cursor() as cursor:
        cursor.execute(query)
        
while(True):
    if(init):
        init = False
        creation_of_database()
        records = read_all_temperature("-1")
        add_record_oracle(records)
        continue
    records = read_all_temperature("-40s")
    add_record_oracle(records)
    
    