from src.connect.connectOracle import connect
from src.model.record import Record
from src.model.alertData  import AlertData
from datetime import datetime
import threading
import time


def read_all_temperature():
    temp = []
    try:
        with connect.cursor() as cursor:
            query = """SELECT captured_time, temperature, host_name, sensor_name
                        FROM cpu_temperature
                        WHERE sensor_name NOT IN (
                            'nct6776_auxtin',
                            'nct6776_cputin',
                            'nct6776_pch_chip_temp',
                            'nct6776_pch_cpu_temp',
                            'nct6776_pch_mch_temp',
                            'nct6776_peci_agent_0',
                            'nct6776_systin'
                        ) and captured_time >= SYSTIMESTAMP - INTERVAL '20' MINUTE"""
            cursor.execute(query)
            for row in cursor.fetchall():
                temp.append(Record(
                        host=row[2],
                        sensor_name=row[3],
                        time= row[0],
                        temperature=row[1]
                    )
                )
        return temp
    except Exception as  e:
        print(e)
        return temp
    
    
def start_background_job(alert_info):
    def job ():
        round = 1
        while True:
            try:
                with connect.cursor() as cursor:
                    cursor.callproc("add_data",[alert_info])
                connect.commit()
                print(f"--- add Data {round}")
            except Exception as e:
                print(f"--- Error: {e}")
            
            time.sleep(5)
            round += 1
    thread = threading.Thread( target=job, daemon=True)
    thread.start()

def set_alert(alert_info):
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    delete_query = """
    BeGIN
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE alert_temperature';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -942 THEN
                    RAISE;
                END IF;
        END;

        execute Immediate'
            CREATE TABLE alert_temperature (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                CAPTURED_TIME TIMESTAMP(6),
                TEMPERATURE BINARY_DOUBLE,
                SENSOR_NAME VARCHAR2(100)
            )';
    END;
    """

    create_proc_sql = """
        create or replace  procedure  add_data(p_alert_threshold in NUMBER) is v_start_date TIMESTAMP;
        begin
            select start_date into v_start_date
            from job_params
            where job_name  = 'job_oracle';

            insert into alert_temperature (id,captured_time, temperature,sensor_name)
            select id,captured_time, temperature, sensor_name 
            from cpu_temperature
            where temperature >= p_alert_threshold and captured_time >= v_start_date and not exists (
                select 1 from alert_temperature where alert_temperature.id  =  cpu_temperature.id
            );

            commit;
        end;
    """

    update_time = f""" MERGE INTO job_params jp
                    USING (SELECT 'job_oracle' AS job_name, TO_TIMESTAMP('{current_time}', 'YYYY-MM-DD HH24:MI:SS') AS start_date FROM dual) src
                    ON (jp.job_name = src.job_name)
                    WHEN MATCHED THEN UPDATE SET jp.start_date = src.start_date
                    WHEN NOT MATCHED THEN INSERT (job_name, start_date) VALUES (src.job_name, src.start_date)
                """


    with connect.cursor() as cursor:
        cursor.execute(delete_query)
        connect.commit()
        cursor.execute(create_proc_sql)
        cursor.execute(update_time)
        
    connect.commit()
    start_background_job(alert_info.temperature)
    return {"status": "Job saved","status_job":"start"}
    

def read_alert():
    temp = []
    try:
        with connect.cursor() as  cursor:
            query = """
                    select  captured_time,temperature,sensor_name from alert_temperature
                        WHERE sensor_name NOT IN (
                            'nct6776_auxtin',
                            'nct6776_cputin',
                            'nct6776_pch_chip_temp',
                            'nct6776_pch_cpu_temp',
                            'nct6776_pch_mch_temp',
                            'nct6776_peci_agent_0',
                            'nct6776_systin'
                        ) and captured_time >= SYSTIMESTAMP - INTERVAL '10' MINUTE
            """
            cursor.execute(query)
            for row  in cursor.fetchall():
                temp.append (AlertData(
                     time= row[0],
                     temperature= row[1],
                     sensor_name= row[2],
            ))
        return temp
    except Exception as  e:
        print(e)
        return  temp